import secrets

from flask import flash
from flask import request
from flask import Blueprint
from flask import render_template

#Flask mail
from Utils import mail
from flask_mail import Message

bp = Blueprint('keygenerator', __name__)

@bp.route('/', methods=['GET', 'POST'])
def index():
    
    if request.method == 'POST':
        
        email = request.form['email']
        sk_client = str( secrets.token_hex() )

        msg = Message()
        msg.subject = "Flask secret key succefully generated"
        msg.add_recipient(email)
        msg.html = "<h3>Hello, here is your flask secret key</3><hr/><br/>"
        msg.html += "<p>Flask secret key:</p>"
        msg.html += "<p><b>"+sk_client+"</b></br/>"
        msg.html += "<small style='text-align:right;'>Thanks for use flask-secret-key-generator.</small></p>"
        msg.charset = 'UTF-8'
        mail.send(msg)    
            
        flash("Email send to: " + email, category="message")        
        
        msg = "Key generated by flask-secret-key-generator"
        data = (email, sk_client, msg)
        return render_template('/key-generator/key-generator.html', data=data)
        
    return render_template('/key-generator/index.html')
    
